import type { NumericSimControl } from "./PanelControls";

export const sidebarChassisControls: readonly NumericSimControl[] = [
  {
    key: "buildWheelbaseMm",
    label: "Motor-to-Motor Diagonal",
    min: 120,
    max: 350,
    step: 1,
    unit: "mm",
  },
  {
    key: "buildPropSizeIn",
    label: "Propeller Size",
    min: 2.5,
    max: 8,
    step: 0.1,
    unit: " in",
  },
  {
    key: "buildBottomPlateThicknessMm",
    label: "Bottom Plate Thickness",
    min: 2,
    max: 8,
    step: 0.5,
    unit: "mm",
  },
  {
    key: "buildTopPlateThicknessMm",
    label: "Top Plate Thickness",
    min: 1,
    max: 4,
    step: 0.5,
    unit: "mm",
  },
  {
    key: "buildStandoffHeightMm",
    label: "Standoff Height",
    min: 15,
    max: 40,
    step: 1,
    unit: "mm",
  },
  {
    key: "buildArmWidthMm",
    label: "Arm Width",
    min: 8,
    max: 25,
    step: 1,
    unit: "mm",
  },
];

export const sidebarMassControls: readonly NumericSimControl[] = [
  {
    key: "buildBatteryMassG",
    label: "Battery Mass",
    min: 40,
    max: 450,
    step: 1,
    unit: " g",
  },
  {
    key: "buildMotorMassG",
    label: "Motor Mass",
    min: 5,
    max: 80,
    step: 1,
    unit: " g",
  },
  {
    key: "buildPropMassG",
    label: "Prop Mass",
    min: 1,
    max: 12,
    step: 0.1,
    unit: " g",
  },
  {
    key: "buildStackMassG",
    label: "Stack Mass",
    min: 5,
    max: 60,
    step: 1,
    unit: " g",
  },
  {
    key: "buildMiscMassG",
    label: "Misc Mass",
    min: 0,
    max: 120,
    step: 1,
    unit: " g",
  },
];

export const engineeringWorldActuatorControls: readonly NumericSimControl[] = [
  {
    key: "ambientTempC",
    label: "Ambient Temperature",
    min: -10,
    max: 45,
    step: 1,
    unit: " C",
  },
  {
    key: "humidityPct",
    label: "Humidity",
    min: 0,
    max: 100,
    step: 5,
    unit: "%",
  },
  {
    key: "meanWindMS",
    label: "Mean Wind",
    min: 0,
    max: 20,
    step: 0.2,
    unit: " m/s",
  },
  {
    key: "gustAmplitudeMS",
    label: "Gust Amplitude",
    min: 0,
    max: 10,
    step: 0.1,
    unit: " m/s",
  },
  {
    key: "turbulenceMS",
    label: "Turbulence",
    min: 0,
    max: 5,
    step: 0.05,
    unit: " m/s",
  },
  {
    key: "escLatencyMs",
    label: "ESC Latency",
    min: 0,
    max: 120,
    step: 2,
    unit: " ms",
  },
  {
    key: "actuatorMismatchPct",
    label: "Actuator Mismatch",
    min: 0,
    max: 20,
    step: 0.5,
    unit: "%",
  },
  {
    key: "motorCurrentLimitA",
    label: "Current Limit",
    min: 20,
    max: 220,
    step: 5,
    unit: " A",
  },
  {
    key: "motorCoolingScale",
    label: "Motor Cooling",
    min: 0.3,
    max: 2,
    step: 0.05,
    unit: "x",
  },
  {
    key: "buildMotorKV",
    label: "Motor KV",
    min: 500,
    max: 4200,
    step: 10,
    unit: " kv",
  },
  {
    key: "buildBatteryCells",
    label: "Battery Cells",
    min: 3,
    max: 8,
    step: 1,
    unit: " s",
  },
  {
    key: "buildPropPitchIn",
    label: "Prop Pitch",
    min: 2,
    max: 8,
    step: 0.1,
    unit: " in",
  },
  {
    key: "buildPackResistanceMilliOhm",
    label: "Pack Resistance",
    min: 4,
    max: 80,
    step: 1,
    unit: " mOhm",
  },
  {
    key: "rotorInertiaScale",
    label: "Rotor Inertia",
    min: 0.35,
    max: 3,
    step: 0.01,
    unit: "x",
  },
  {
    key: "acroRateDegPerSec",
    label: "Acro Rate",
    min: 360,
    max: 1400,
    step: 10,
    unit: " deg/s",
  },
  {
    key: "acroExpo",
    label: "Acro Expo",
    min: 0,
    max: 0.75,
    step: 0.01,
  },
  {
    key: "airmodeStrength",
    label: "Air-Mode Authority",
    min: 0,
    max: 1,
    step: 0.01,
  },
  {
    key: "propWashCoupling",
    label: "Prop-Wash Coupling",
    min: 0,
    max: 1,
    step: 0.01,
  },
];

export const engineeringStructureControls: readonly NumericSimControl[] = [
  {
    key: "manufacturingToleranceMm",
    label: "Manufacturing Tolerance",
    min: 0.01,
    max: 0.5,
    step: 0.01,
    unit: " mm",
  },
  {
    key: "materialDensityGcm3",
    label: "Material Density",
    min: 1,
    max: 2.2,
    step: 0.01,
    unit: " g/cc",
  },
  {
    key: "materialElasticModulusGPa",
    label: "Elastic Modulus",
    min: 20,
    max: 140,
    step: 1,
    unit: " GPa",
  },
  {
    key: "materialYieldStrengthMPa",
    label: "Yield Strength",
    min: 120,
    max: 1200,
    step: 10,
    unit: " MPa",
  },
  {
    key: "materialBrittleStrainPct",
    label: "Brittle Strain Limit",
    min: 0.2,
    max: 3,
    step: 0.01,
    unit: " %",
  },
  {
    key: "impactFragilityScale",
    label: "Impact Fragility",
    min: 0.25,
    max: 3,
    step: 0.01,
    unit: "x",
  },
  {
    key: "wireOuterDiameterMm",
    label: "Wire Outer Diameter",
    min: 0.6,
    max: 4,
    step: 0.05,
    unit: " mm",
  },
  {
    key: "wiringBundleCount",
    label: "Harness Conductors",
    min: 1,
    max: 24,
    step: 1,
  },
  {
    key: "wiringMinSpacingMm",
    label: "Wire Keepout",
    min: 1,
    max: 12,
    step: 0.1,
    unit: " mm",
  },
  {
    key: "wiringCurrentA",
    label: "Harness Current",
    min: 1,
    max: 180,
    step: 1,
    unit: " A",
  },
  {
    key: "motorScrewClearanceMm",
    label: "Motor Screw Clearance",
    min: 0.05,
    max: 1,
    step: 0.01,
    unit: " mm",
  },
  {
    key: "stackScrewClearanceMm",
    label: "Stack Screw Clearance",
    min: 0.05,
    max: 1,
    step: 0.01,
    unit: " mm",
  },
  {
    key: "cameraTpuClearanceMm",
    label: "Camera TPU Clearance",
    min: 0.1,
    max: 2,
    step: 0.01,
    unit: " mm",
  },
  {
    key: "antennaTubeClearanceMm",
    label: "Antenna Tube Clearance",
    min: 0.1,
    max: 2,
    step: 0.01,
    unit: " mm",
  },
  {
    key: "stackHeightMm",
    label: "Stack Height",
    min: 4,
    max: 30,
    step: 0.5,
    unit: " mm",
  },
  {
    key: "armFractureForceN",
    label: "Arm Fracture Threshold",
    min: 80,
    max: 2000,
    step: 10,
    unit: " N",
  },
  {
    key: "motorDamageForceN",
    label: "Motor Damage Threshold",
    min: 40,
    max: 1200,
    step: 10,
    unit: " N",
  },
  {
    key: "batteryDamageForceN",
    label: "Battery Damage Threshold",
    min: 60,
    max: 1600,
    step: 10,
    unit: " N",
  },
];

export const engineeringRateControls: readonly NumericSimControl[] = [
  {
    key: "betaflightRcRate",
    label: "BF RC Rate",
    min: 0.2,
    max: 3,
    step: 0.01,
  },
  {
    key: "betaflightSuperRate",
    label: "BF Super Rate",
    min: 0,
    max: 0.95,
    step: 0.01,
  },
  {
    key: "betaflightExpo",
    label: "BF Expo",
    min: 0,
    max: 0.95,
    step: 0.01,
  },
  {
    key: "betaflightYawRcRate",
    label: "BF Yaw RC Rate",
    min: 0.2,
    max: 3,
    step: 0.01,
  },
  {
    key: "betaflightYawSuperRate",
    label: "BF Yaw Super",
    min: 0,
    max: 0.95,
    step: 0.01,
  },
  {
    key: "betaflightYawExpo",
    label: "BF Yaw Expo",
    min: 0,
    max: 0.95,
    step: 0.01,
  },
  {
    key: "throttleMid01",
    label: "Throttle Mid",
    min: 0.05,
    max: 0.95,
    step: 0.01,
  },
  {
    key: "throttleExpo",
    label: "Throttle Expo",
    min: 0,
    max: 0.95,
    step: 0.01,
  },
];

export const engineeringSensorControls: readonly NumericSimControl[] = [
  {
    key: "sensorNoiseScale",
    label: "Sensor Noise",
    min: 0,
    max: 2,
    step: 0.05,
    unit: "x",
  },
  {
    key: "gpsRateHz",
    label: "GPS Update Rate",
    min: 1,
    max: 20,
    step: 1,
    unit: " Hz",
  },
  {
    key: "sensorLogSeconds",
    label: "Recorder Window",
    min: 10,
    max: 180,
    step: 5,
    unit: " s",
  },
];
