import { FlightTelemetry, SimSettings } from "../../types";

export function createSimSettingsTelemetrySnapshot(
  simSettings: SimSettings,
  overrides: Partial<FlightTelemetry> = {},
): Partial<FlightTelemetry> {
  return {
    buildWheelbaseMm: simSettings.buildWheelbaseMm,
    buildPropSizeIn: simSettings.buildPropSizeIn,
    buildArmWidthMm: simSettings.buildArmWidthMm,
    buildBottomPlateThicknessMm: simSettings.buildBottomPlateThicknessMm,
    buildTopPlateThicknessMm: simSettings.buildTopPlateThicknessMm,
    buildStandoffHeightMm: simSettings.buildStandoffHeightMm,
    buildFcMountMm: simSettings.buildFcMountMm,
    buildMotorMountPatternMm: simSettings.buildMotorMountPatternMm,
    buildMotorShaftHoleMm: simSettings.buildMotorShaftHoleMm,
    buildBatteryMassG: simSettings.buildBatteryMassG,
    buildMotorMassG: simSettings.buildMotorMassG,
    buildPropMassG: simSettings.buildPropMassG,
    buildStackMassG: simSettings.buildStackMassG,
    buildMiscMassG: simSettings.buildMiscMassG,
    buildMotorKV: simSettings.buildMotorKV,
    buildBatteryCells: simSettings.buildBatteryCells,
    buildPropPitchIn: simSettings.buildPropPitchIn,
    buildPackResistanceMilliOhm: simSettings.buildPackResistanceMilliOhm,
    rotorInertiaScale: simSettings.rotorInertiaScale,
    acroRateDegPerSec: simSettings.acroRateDegPerSec,
    acroExpo: simSettings.acroExpo,
    airmodeStrength: simSettings.airmodeStrength,
    propWashCoupling: simSettings.propWashCoupling,
    rateProfileMode: simSettings.rateProfileMode,
    betaflightRcRate: simSettings.betaflightRcRate,
    betaflightSuperRate: simSettings.betaflightSuperRate,
    betaflightExpo: simSettings.betaflightExpo,
    betaflightYawRcRate: simSettings.betaflightYawRcRate,
    betaflightYawSuperRate: simSettings.betaflightYawSuperRate,
    betaflightYawExpo: simSettings.betaflightYawExpo,
    throttleMid01: simSettings.throttleMid01,
    throttleExpo: simSettings.throttleExpo,
    ...overrides,
  };
}

export function createResetFlightTelemetry({
  actuatorSpreadPct,
  simSettings,
  totalMassG,
}: {
  actuatorSpreadPct: number;
  simSettings: SimSettings;
  totalMassG: number;
}): FlightTelemetry {
  return {
    throttle01: 0,
    thrustN: 0,
    weightN: 0,
    tw: 0,
    altitudeM: 0,
    speedMS: 0,
    airspeedMS: 0,
    windMS: 0,
    groundEffectMult: 1,
    batteryV: 0,
    batteryI: 0,
    batterySagV: 0,
    totalMassG,
    armed: false,
    ambientTempC: simSettings.ambientTempC,
    pressurePa: 101325,
    airDensityKgM3: 1.225,
    gustMS: 0,
    actuatorSpreadPct,
    gpsAltitudeM: 0,
    gpsSpeedMS: 0,
    baroAltitudeM: 0,
    rangefinderM: 0,
    headingDeg: 0,
    gyroDps: 0,
    accelMS2: 0,
    motorTempsC: [
      simSettings.ambientTempC,
      simSettings.ambientTempC,
      simSettings.ambientTempC,
      simSettings.ambientTempC,
    ],
    motorCurrentsA: [0, 0, 0, 0],
    avgMotorTempC: simSettings.ambientTempC,
    peakMotorTempC: simSettings.ambientTempC,
    currentLimitA: simSettings.motorCurrentLimitA,
    currentLimitScale: 1,
    thermalLimitScale: 1,
    ...createSimSettingsTelemetrySnapshot(simSettings),
    propWashLoss: 0,
    rotorReloadLoss: 0,
    logSamples: 0,
    logDurationSec: 0,
    gpsSampleAgeSec: Number.POSITIVE_INFINITY,
    baroSampleAgeSec: Number.POSITIVE_INFINITY,
    rangefinderSampleAgeSec: Number.POSITIVE_INFINITY,
    magnetometerSampleAgeSec: Number.POSITIVE_INFINITY,
    gyroSampleAgeSec: Number.POSITIVE_INFINITY,
    accelSampleAgeSec: Number.POSITIVE_INFINITY,
    lastImpactForceN: 0,
    lastImpactAgeSec: Number.POSITIVE_INFINITY,
    contactCount: 0,
  };
}
