import {
  DebugPreset,
  DebugSettings,
  DroneParams,
  SimSettings,
  ViewSettings,
} from "../../types";

export const defaultParams: DroneParams = {
  frameSize: 210,
  plateThickness: 5,
  topPlateThickness: 2,
  standoffHeight: 25,
  armWidth: 14,
  fcMounting: 30.5,
  motorMountPattern: 16,
  motorCenterHole: 6,
  weightReduction: 40,
  propSize: 5.1,
  showTPU: true,
  tpuColor: "#0ea5e9",
  viewMode: "assembled",
};

export const defaultViewSettings: ViewSettings = {
  wireframe: false,
  focus: "all",
  inspectTarget: "all",
  keepContext: true,
  visibility: {
    frame: true,
    propulsion: true,
    electronics: true,
    accessories: true,
  },
};

export const defaultDebugSettings: DebugSettings = {
  debugPreset: "minimal",
  debugInspector: false,
  physicsLines: false,
  flightTelemetry: false,
  sensorOverlays: false,
  sensorFrustums: false,
  forceVectors: false,
  collisionVolumes: false,
  impactEvents: false,
  windField: false,
  flightTrail: false,
};

export type NonCustomDebugPreset = Exclude<DebugPreset, "custom">;

export const debugPresetValues: readonly DebugPreset[] = [
  "custom",
  "minimal",
  "sensors",
  "aero",
  "collisions",
  "full",
];

const sharedDebugPresets: Record<
  NonCustomDebugPreset,
  Omit<DebugSettings, "debugPreset">
> = {
  minimal: {
    debugInspector: false,
    physicsLines: false,
    flightTelemetry: false,
    sensorOverlays: false,
    sensorFrustums: false,
    forceVectors: false,
    collisionVolumes: false,
    impactEvents: false,
    windField: false,
    flightTrail: false,
  },
  sensors: {
    debugInspector: true,
    physicsLines: false,
    flightTelemetry: true,
    sensorOverlays: true,
    sensorFrustums: true,
    forceVectors: false,
    collisionVolumes: false,
    impactEvents: false,
    windField: false,
    flightTrail: false,
  },
  aero: {
    debugInspector: true,
    physicsLines: false,
    flightTelemetry: true,
    sensorOverlays: true,
    sensorFrustums: false,
    forceVectors: true,
    collisionVolumes: false,
    impactEvents: false,
    windField: true,
    flightTrail: true,
  },
  collisions: {
    debugInspector: true,
    physicsLines: true,
    flightTelemetry: true,
    sensorOverlays: false,
    sensorFrustums: false,
    forceVectors: false,
    collisionVolumes: true,
    impactEvents: true,
    windField: false,
    flightTrail: false,
  },
  full: {
    debugInspector: true,
    physicsLines: true,
    flightTelemetry: true,
    sensorOverlays: true,
    sensorFrustums: true,
    forceVectors: true,
    collisionVolumes: true,
    impactEvents: true,
    windField: true,
    flightTrail: true,
  },
};

export const debugPresetOptions: ReadonlyArray<{
  label: string;
  value: DebugPreset;
}> = [
  { label: "Minimal", value: "minimal" },
  { label: "Sensors", value: "sensors" },
  { label: "Aerodynamics", value: "aero" },
  { label: "Collisions", value: "collisions" },
  { label: "Full Lab Debug", value: "full" },
  { label: "Custom", value: "custom" },
];

export function applyDebugPreset(preset: NonCustomDebugPreset): DebugSettings {
  return {
    debugPreset: preset,
    ...sharedDebugPresets[preset],
  };
}

export const defaultSimSettings: SimSettings = {
  motorAudioEnabled: false,
  motorAudioVolume: 0.35,
  vibrationAmount: 0.35,
  environmentPreset: "lab_calm",
  ambientTempC: 20,
  humidityPct: 45,
  meanWindMS: 0,
  gustAmplitudeMS: 0,
  turbulenceMS: 0,
  escLatencyMs: 8,
  actuatorMismatchPct: 0,
  sensorNoiseScale: 0.15,
  gpsRateHz: 10,
  gpsEnabled: true,
  barometerEnabled: true,
  magnetometerEnabled: true,
  rangefinderEnabled: true,
  motorCurrentLimitA: 120,
  motorCoolingScale: 1,
  buildWheelbaseMm: 210,
  buildPropSizeIn: 5.1,
  buildArmWidthMm: 14,
  buildBottomPlateThicknessMm: 5,
  buildTopPlateThicknessMm: 2,
  buildStandoffHeightMm: 25,
  buildFcMountMm: 30.5,
  buildMotorMountPatternMm: 16,
  buildMotorShaftHoleMm: 6,
  buildBatteryMassG: 180,
  buildMotorMassG: 32,
  buildPropMassG: 4.1,
  buildStackMassG: 18,
  buildMiscMassG: 20,
  manufacturingToleranceMm: 0.05,
  materialDensityGcm3: 1.6,
  materialElasticModulusGPa: 70,
  materialYieldStrengthMPa: 600,
  materialBrittleStrainPct: 1.1,
  impactFragilityScale: 1,
  wireOuterDiameterMm: 1.6,
  wiringBundleCount: 8,
  wiringMinSpacingMm: 3,
  wiringCurrentA: 45,
  motorScrewClearanceMm: 0.25,
  stackScrewClearanceMm: 0.2,
  cameraTpuClearanceMm: 0.45,
  antennaTubeClearanceMm: 0.35,
  stackHeightMm: 14,
  armFractureForceN: 420,
  motorDamageForceN: 220,
  batteryDamageForceN: 320,
  buildMotorKV: 1950,
  buildBatteryCells: 6,
  buildPropPitchIn: 4.3,
  buildPackResistanceMilliOhm: 20,
  rotorInertiaScale: 1,
  acroRateDegPerSec: 820,
  acroExpo: 0.3,
  airmodeStrength: 0.72,
  propWashCoupling: 0.68,
  rateProfileMode: "actual",
  betaflightRcRate: 1.2,
  betaflightSuperRate: 0.72,
  betaflightExpo: 0.1,
  betaflightYawRcRate: 1,
  betaflightYawSuperRate: 0.62,
  betaflightYawExpo: 0.05,
  throttleMid01: 0.5,
  throttleExpo: 0,
  sensorLogSeconds: 45,
};
